{
 "title": "Self-hosted Teleport Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "teleport_job",
    "query": {
     "query": "label_values(teleport_build_info,job)"
    }
   },
   {
    "name": "backend_metrics",
    "query": {
     "query": "{__name__=~\"backend_.*_requests_total\",namespace=\"$namespace\", component=\"backend\", job=~\"$teleport_job\"}"
    }
   },
   {
    "name": "cache_metrics",
    "query": {
     "query": "{__name__=~\"backend_.*_requests_total\",namespace=\"$namespace\", component=\"cache\", job=~\"$teleport_job\"}"
    }
   },
   {
    "name": "metrics_per",
    "query": {
     "query": "label_names(teleport_build_info)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(teleport_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Teleport Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Teleport Build Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(job, goversion, version) (teleport_build_info{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Teleport Versions",
   "type": "piechart",
   "description": "The number of Teleport services that are connected to an Auth Service instance grouped by version.",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Teleport Versions",
   "type": "timeseries",
   "description": "Count and version of Teleport agents connected to Teleport Cloud.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum(teleport_registered_servers{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Teleport Process State",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_state{namespace=\"$namespace\", job=~\"$teleport_job\"}",
     "legendFormat": "{{$metrics_per}}"
    }
   ]
  },
  {
   "title": "Login count",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(user_login_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))",
     "legendFormat": "User login count"
    },
    {
     "expr": "sum(rate(failed_login_attempts_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))",
     "legendFormat": "Failed login attempts"
    }
   ]
  },
  {
   "title": "Connected Resources",
   "type": "stat",
   "description": "Number of resources connected to Teleport Cluster.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(teleport_connected_resources{namespace=\"$namespace\", job=~\"$teleport_job\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Tunnels",
   "type": "stat",
   "description": "Number of reverse SSH tunnels connected to the Teleport Proxy Service by Teleport instances.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (teleport_reverse_tunnels_connected{namespace=\"$namespace\", job=~\"$teleport_job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Managed Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rollout Spec",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "count(teleport_agent_autoupdates_rollout_start{namespace=\"$namespace\", job=~\"$teleport_job\"} == 1) by (version)",
       "legendFormat": "start version"
      },
      {
       "expr": "count(teleport_agent_autoupdates_rollout_target{namespace=\"$namespace\", job=~\"$teleport_job\"} == 1) by (version)",
       "legendFormat": "target version"
      }
     ]
    },
    {
     "title": "Teleport Agent Updates Settings",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 21 },
     "targets": [
      {
       "expr": "max by(__name__) ({__name__=~\"teleport_agent_autoupdates_.*_present\", namespace=\"$namespace\", job=~\"$teleport_job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auto Update Mode",
     "type": "state-timeline",
     "description": "Automatic updates can be controlled both by customers and us. We control them through autoupdate_version, and customers control the autoupdate_config resource. The autoudpate_agent_rollout resource is the combination of both settings.",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 21 },
     "targets": [
      {
       "expr": "max by(__name__) ({__name__=~\"teleport_agent_autoupdates_.*_mode\", namespace=\"$namespace\", job=~\"$teleport_job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollout State",
     "type": "state-timeline",
     "description": "The rollout state aggregates the state of every group. It becomes active as soon when the first group is udpated, and done when the last group is updated.\n\nThe operator takes update decision based on this state. For example, if we had an unstarted v1 -> v2 rollout and we want to update to v3, the operator will chose to do v1 -> v3 instead of v2 -> v3.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "max(teleport_agent_autoupdates_rollout_state{namespace=\"$namespace\", job=~\"$teleport_job\"}) ",
       "legendFormat": "State "
      },
      {
       "expr": "max(teleport_agent_autoupdates_rollout_group_state{namespace=\"$namespace\", job=~\"$teleport_job\"}) by (group_number)",
       "legendFormat": "Group {{group_number}}"
      }
     ]
    },
    {
     "title": "Reconciliations Triggered Rate (minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "r/m" } },
     "targets": [
      {
       "expr": "avg by(result)(rate(teleport_agent_autoupdates_reconciliations_total{namespace=\"$namespace\", job=~\"$teleport_job\"}[5m])*60)",
       "legendFormat": "[{{result}}] reconciliation "
      },
      {
       "expr": "avg by(result)(rate(teleport_agent_autoupdates_reconciliation_tries_total{namespace=\"$namespace\", job=~\"$teleport_job\"}[5m])*60)",
       "legendFormat": "[{{result}}] attempt"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Write Availability",
     "type": "state-timeline",
     "description": "Percentage of write requests to the backend that succeed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "\n1 - ((\n        sum by ($metrics_per) (rate(backend_write_requests_failed_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval]))\n        - \n        sum by ($metrics_per) (rate(teleport_backend_write_requests_failed_precondition_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])) OR on() vector(0)\n    ) / (\n        sum by ($metrics_per) (rate(backend_write_requests_total{component=\"backend\",namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])) OR on() vector(1)\n    ))\n",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Backend Read Availability",
     "type": "state-timeline",
     "description": "Percentage of write requests to the backend that succeed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1- ((\n    (\n        (sum by ($metrics_per) (rate(backend_read_requests_failed_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval])) OR vector(0))\n            /\n        (sum by ($metrics_per) (rate(backend_read_requests_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval])) OR on() vector(1))\n    )\n  )) or group by ($metrics_per) (rate(backend_read_requests_total{component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[[backend_metrics]]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "repeat": "backend_metrics",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=\"[[backend_metrics]]_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Count"
      },
      {
       "expr": "sum(rate({__name__=\"[[backend_metrics]]_failed_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Failed Count"
      },
      {
       "expr": "sum(rate({__name__=\"teleport_[[backend_metrics]]_failed_precondition_total\",component=\"backend\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Precondition Failed Count"
      }
     ]
    },
    {
     "title": "[cache] [[cache_metrics]]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "repeat": "cache_metrics",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=\"[[cache_metrics]]_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Count"
      },
      {
       "expr": "sum(rate({__name__=\"[[cache_metrics]]_failed_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Failed Count"
      },
      {
       "expr": "sum(rate({__name__=\"teleport_[[cache_metrics]]_failed_precondition_total\",component=\"cache\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total Precondition Failed Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(teleport_audit_emit_events{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval]))",
       "legendFormat": "Emitted"
      },
      {
       "expr": "sum(rate(audit_failed_emit_events{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval]))",
       "legendFormat": "Failed to emit"
      }
     ]
    },
    {
     "title": "Watcher Events by Resource",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(watcher_events_count{namespace=\"$namespace\", job=~\"$teleport_job\"}[$__rate_interval])) by (resource)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      },
      {
       "expr": "(go_gc_gomemlimit_bytes{namespace=\"$namespace\",job=~\"$teleport_job\"} < 9000000000000000000)",
       "legendFormat": "GOMEMLIMIT {{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "CPU/s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])",
       "legendFormat": "{{$metrics_per}}"
      },
      {
       "expr": "go_sched_gomaxprocs_threads{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "GOMAXPROCS {{$metrics_per}}"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 71 },
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\",job=~\"$teleport_job\"}",
       "legendFormat": "{{$metrics_per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPCs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Invocations Handled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"$teleport_job\"}[$__rate_interval])) by (grpc_service, grpc_method)",
       "legendFormat": "{{grpc_service}}/{{grpc_method}}"
      }
     ]
    },
    {
     "title": "RPC Invocations Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",grpc_code!=\"OK\",job=~\"$teleport_job\"}[$__rate_interval])) by (grpc_service, grpc_method, grpc_code)",
       "legendFormat": "{{grpc_service}}/{{grpc_method}} - {{grpc_code}}"
      }
     ]
    }
   ]
  }
 ]
}